language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6" # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev" # 3.8 development branch
  - "nightly" # nightly build
# command to install dependencies
install:
  - curl -L https://github.com/google/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf
  - make setup
  - source ./activate
script:
  - python -m pytest
