# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scripts/protobuf/PoeTrade/request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scripts/protobuf/PoeTrade/request.proto',
  package='PoETrade.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\'scripts/protobuf/PoeTrade/request.proto\x12\x0ePoETrade.proto\"7\n\x0fPoeTradeRequest\x12$\n\x05query\x18\x01 \x01(\x0b\x32\x15.PoETrade.proto.Query\"\x9a\x01\n\x05Query\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12&\n\x06status\x18\x03 \x01(\x0b\x32\x16.PoETrade.proto.Status\x12\'\n\x07\x66ilters\x18\x04 \x01(\x0b\x32\x16.PoETrade.proto.Filter\x12$\n\x05stats\x18\x05 \x03(\x0b\x32\x15.PoETrade.proto.Stats\"\x18\n\x06Status\x12\x0e\n\x06option\x18\x01 \x01(\t\"B\n\x05Stats\x12\x0c\n\x04type\x18\x01 \x01(\t\x12+\n\x07\x66ilters\x18\x02 \x03(\x0b\x32\x1a.PoETrade.proto.StatFilter\"V\n\nStatFilter\x12\n\n\x02id\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.PoETrade.proto.FilterRange\x12\x10\n\x08\x64isabled\x18\x03 \x01(\t\">\n\x06\x46ilter\x12\x34\n\x0eweapon_filters\x18\x01 \x01(\x0b\x32\x1c.PoETrade.proto.WeaponFilter\"N\n\x0cWeaponFilter\x12\x10\n\x08\x64isabled\x18\x01 \x01(\t\x12,\n\x07\x66ilters\x18\x02 \x01(\x0b\x32\x1b.PoETrade.proto.WeaponStats\"\x8f\x02\n\x0bWeaponStats\x12+\n\x06\x64\x61mage\x18\x01 \x01(\x0b\x32\x1b.PoETrade.proto.FilterRange\x12)\n\x04\x63rit\x18\x02 \x01(\x0b\x32\x1b.PoETrade.proto.FilterRange\x12(\n\x03\x61ps\x18\x03 \x01(\x0b\x32\x1b.PoETrade.proto.FilterRange\x12(\n\x03\x64ps\x18\x04 \x01(\x0b\x32\x1b.PoETrade.proto.FilterRange\x12)\n\x04\x65\x64ps\x18\x05 \x01(\x0b\x32\x1b.PoETrade.proto.FilterRange\x12)\n\x04pdps\x18\x06 \x01(\x0b\x32\x1b.PoETrade.proto.FilterRange\"\'\n\x0b\x46ilterRange\x12\x0b\n\x03min\x18\x01 \x01(\t\x12\x0b\n\x03max\x18\x02 \x01(\tb\x06proto3'
)




_POETRADEREQUEST = _descriptor.Descriptor(
  name='PoeTradeRequest',
  full_name='PoETrade.proto.PoeTradeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='PoETrade.proto.PoeTradeRequest.query', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=114,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='PoETrade.proto.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PoETrade.proto.Query.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='PoETrade.proto.Query.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='PoETrade.proto.Query.status', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filters', full_name='PoETrade.proto.Query.filters', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stats', full_name='PoETrade.proto.Query.stats', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=271,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='PoETrade.proto.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='option', full_name='PoETrade.proto.Status.option', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=297,
)


_STATS = _descriptor.Descriptor(
  name='Stats',
  full_name='PoETrade.proto.Stats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='PoETrade.proto.Stats.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filters', full_name='PoETrade.proto.Stats.filters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=365,
)


_STATFILTER = _descriptor.Descriptor(
  name='StatFilter',
  full_name='PoETrade.proto.StatFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PoETrade.proto.StatFilter.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PoETrade.proto.StatFilter.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disabled', full_name='PoETrade.proto.StatFilter.disabled', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=453,
)


_FILTER = _descriptor.Descriptor(
  name='Filter',
  full_name='PoETrade.proto.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weapon_filters', full_name='PoETrade.proto.Filter.weapon_filters', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=517,
)


_WEAPONFILTER = _descriptor.Descriptor(
  name='WeaponFilter',
  full_name='PoETrade.proto.WeaponFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='disabled', full_name='PoETrade.proto.WeaponFilter.disabled', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filters', full_name='PoETrade.proto.WeaponFilter.filters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=597,
)


_WEAPONSTATS = _descriptor.Descriptor(
  name='WeaponStats',
  full_name='PoETrade.proto.WeaponStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='damage', full_name='PoETrade.proto.WeaponStats.damage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crit', full_name='PoETrade.proto.WeaponStats.crit', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aps', full_name='PoETrade.proto.WeaponStats.aps', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dps', full_name='PoETrade.proto.WeaponStats.dps', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edps', full_name='PoETrade.proto.WeaponStats.edps', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pdps', full_name='PoETrade.proto.WeaponStats.pdps', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=871,
)


_FILTERRANGE = _descriptor.Descriptor(
  name='FilterRange',
  full_name='PoETrade.proto.FilterRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='PoETrade.proto.FilterRange.min', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='PoETrade.proto.FilterRange.max', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=873,
  serialized_end=912,
)

_POETRADEREQUEST.fields_by_name['query'].message_type = _QUERY
_QUERY.fields_by_name['status'].message_type = _STATUS
_QUERY.fields_by_name['filters'].message_type = _FILTER
_QUERY.fields_by_name['stats'].message_type = _STATS
_STATS.fields_by_name['filters'].message_type = _STATFILTER
_STATFILTER.fields_by_name['value'].message_type = _FILTERRANGE
_FILTER.fields_by_name['weapon_filters'].message_type = _WEAPONFILTER
_WEAPONFILTER.fields_by_name['filters'].message_type = _WEAPONSTATS
_WEAPONSTATS.fields_by_name['damage'].message_type = _FILTERRANGE
_WEAPONSTATS.fields_by_name['crit'].message_type = _FILTERRANGE
_WEAPONSTATS.fields_by_name['aps'].message_type = _FILTERRANGE
_WEAPONSTATS.fields_by_name['dps'].message_type = _FILTERRANGE
_WEAPONSTATS.fields_by_name['edps'].message_type = _FILTERRANGE
_WEAPONSTATS.fields_by_name['pdps'].message_type = _FILTERRANGE
DESCRIPTOR.message_types_by_name['PoeTradeRequest'] = _POETRADEREQUEST
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Stats'] = _STATS
DESCRIPTOR.message_types_by_name['StatFilter'] = _STATFILTER
DESCRIPTOR.message_types_by_name['Filter'] = _FILTER
DESCRIPTOR.message_types_by_name['WeaponFilter'] = _WEAPONFILTER
DESCRIPTOR.message_types_by_name['WeaponStats'] = _WEAPONSTATS
DESCRIPTOR.message_types_by_name['FilterRange'] = _FILTERRANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PoeTradeRequest = _reflection.GeneratedProtocolMessageType('PoeTradeRequest', (_message.Message,), {
  'DESCRIPTOR' : _POETRADEREQUEST,
  '__module__' : 'scripts.protobuf.PoeTrade.request_pb2'
  # @@protoc_insertion_point(class_scope:PoETrade.proto.PoeTradeRequest)
  })
_sym_db.RegisterMessage(PoeTradeRequest)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'scripts.protobuf.PoeTrade.request_pb2'
  # @@protoc_insertion_point(class_scope:PoETrade.proto.Query)
  })
_sym_db.RegisterMessage(Query)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'scripts.protobuf.PoeTrade.request_pb2'
  # @@protoc_insertion_point(class_scope:PoETrade.proto.Status)
  })
_sym_db.RegisterMessage(Status)

Stats = _reflection.GeneratedProtocolMessageType('Stats', (_message.Message,), {
  'DESCRIPTOR' : _STATS,
  '__module__' : 'scripts.protobuf.PoeTrade.request_pb2'
  # @@protoc_insertion_point(class_scope:PoETrade.proto.Stats)
  })
_sym_db.RegisterMessage(Stats)

StatFilter = _reflection.GeneratedProtocolMessageType('StatFilter', (_message.Message,), {
  'DESCRIPTOR' : _STATFILTER,
  '__module__' : 'scripts.protobuf.PoeTrade.request_pb2'
  # @@protoc_insertion_point(class_scope:PoETrade.proto.StatFilter)
  })
_sym_db.RegisterMessage(StatFilter)

Filter = _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), {
  'DESCRIPTOR' : _FILTER,
  '__module__' : 'scripts.protobuf.PoeTrade.request_pb2'
  # @@protoc_insertion_point(class_scope:PoETrade.proto.Filter)
  })
_sym_db.RegisterMessage(Filter)

WeaponFilter = _reflection.GeneratedProtocolMessageType('WeaponFilter', (_message.Message,), {
  'DESCRIPTOR' : _WEAPONFILTER,
  '__module__' : 'scripts.protobuf.PoeTrade.request_pb2'
  # @@protoc_insertion_point(class_scope:PoETrade.proto.WeaponFilter)
  })
_sym_db.RegisterMessage(WeaponFilter)

WeaponStats = _reflection.GeneratedProtocolMessageType('WeaponStats', (_message.Message,), {
  'DESCRIPTOR' : _WEAPONSTATS,
  '__module__' : 'scripts.protobuf.PoeTrade.request_pb2'
  # @@protoc_insertion_point(class_scope:PoETrade.proto.WeaponStats)
  })
_sym_db.RegisterMessage(WeaponStats)

FilterRange = _reflection.GeneratedProtocolMessageType('FilterRange', (_message.Message,), {
  'DESCRIPTOR' : _FILTERRANGE,
  '__module__' : 'scripts.protobuf.PoeTrade.request_pb2'
  # @@protoc_insertion_point(class_scope:PoETrade.proto.FilterRange)
  })
_sym_db.RegisterMessage(FilterRange)


# @@protoc_insertion_point(module_scope)
